Explicitly probe for frr-k8s webhook readiness
Signed-off-by: Jaime Caamaño Ruiz <jcaamano@redhat.com>

diff --git a/contrib/kind-common b/contrib/kind-common
--- a/contrib/kind-common
+++ b/contrib/kind-common
@@ -785,6 +785,28 @@ install_ffr_k8s() {
       sed -i "${LINE_NUM}a\\${IPv6_LINE}" receive_filtered.yaml
     done
   fi
+  
+  # frr-k8s webhook is declaring readiness before its endpoint is serving.
+  # Let's do our own probing. Also will print logs in case of failure so we get
+  # insights on why this is hapenning 
+  local r
+  r=0
+  timeout 60s bash -x <<EOF || r=$?
+echo "Attempting to reach frr-k8s webhook"
+kind export kubeconfig --name ovn
+while true; do
+docker exec ovn-control-plane curl -ksS --connect-timeout 0.1 https://$(kubectl get svc -n frr-k8s-system frr-k8s-webhook-service -o jsonpath='{.spec.clusterIP}')
+[ \$? -eq 0 ] && exit 0
+echo "Couldn't reach frr-k8s webhook, trying in 1s..."
+sleep 1s
+done
+EOF
+  echo "r=$r"
+  if [ "$r" -ne "0" ]; then
+    kubectl describe pod -n frr-k8s-system -l app=frr-k8s-webhook-server
+    kubectl logs -n frr-k8s-system -l app=frr-k8s-webhook-server
+  fi
+
   kubectl apply -n frr-k8s-system -f receive_filtered.yaml
   popd || exit 1
 
