DNM/TEST: checking if u/s 5617 PR works d/s
Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>

diff --git a/go-controller/Makefile b/go-controller/Makefile
--- a/go-controller/Makefile
+++ b/go-controller/Makefile
@@ -94,7 +94,8 @@ lint:
 ifeq ($(CONTAINER_RUNNABLE), 0)
 	@GOPATH=${GOPATH} ./hack/lint.sh $(CONTAINER_RUNTIME) || { echo "lint failed! Try running 'make lint-fix'"; exit 1; }
 else
-	echo "linter can only be run within a container since it needs a specific golangci-lint version"; exit 1
+	echo "no container runtime. attempting to run natively";
+	@GOPATH=${GOPATH} ./hack/lint.sh run-natively || { echo "running lint locally failed!"; exit 1; }
 endif
 
 lint-fix:
@@ -102,7 +103,9 @@ ifeq ($(CONTAINER_RUNNABLE), 0)
 	@GOPATH=${GOPATH} ./hack/lint.sh $(CONTAINER_RUNTIME) fix || { echo "ERROR: lint fix failed! There is a bug that changes file ownership to root \
 	when this happens. To fix it, simply run 'chown -R <user>:<group> *' from the repo root."; exit 1; }
 else
-	echo "linter can only be run within a container since it needs a specific golangci-lint version"; exit 1
+	echo "no container runtime. attempting to run natively w/ -fix flag";
+	@GOPATH=${GOPATH} ./hack/lint.sh run-natively fix || { echo "running lint fix locally failed! There is a bug that changes file ownership to root \
+	when this happens. To fix it, simply run 'chown -R <user>:<group> *' from the repo root."; exit 1; }
 endif
 
 gofmt:
